### ISSUE TITLE
suggest about headers

### ISSUE THREAD

**Issue by sunwangme** [SLIBIO/SLib#2]
hi, thanks for so nice lib!!!
i have some suggest about headers.

1. rename the root dir "inc"  to "include"
2. change the include rule "../../../inc/slib/xxx/xxx.h" to "slib/xxx/xxx.h" 
    do it to all header and src,just as google c++ guide.

example: SLib/src/slib/core/base.cpp
#include "../../../inc/slib/core/base.h" ==> #include "slib/core/base.h"

example:SLib/inc/slib/core/base.h
#include "definition.h" ==> #include "slib/core/definition.h"

**Comment by fred1218zh** [comment]
Thanks for your suggest.

1. Since we are already running many projects based on this library, so that I don't prefer to rename the directory structure. Instead, we can use the suggested directory structure to the precompiled package (for the users) which will be available soon.

2. #include "../../../inc/slib..." should be changed to #include <slib/...>. I will create new issue for this change.

3. I'm not sure that it is necessary to change the #include statements in header files. We need to discuss more.

Thanks again.

**Comment by sunwangme** [comment]
ok
